version: "3.9"
services:
  pocketbase:
    build:
      context: ./pocketbase
    image: local/pocketbase2
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/pb_data
